"""
Complex path: decompose -> multiple retrievals -> answer, generated by
GPT-4o-mini (OpenAI).

No tool-calling -- the classifier already decided this query is
"complex", so this pipeline always:
  1. asks GPT-4o-mini to decompose the question into 2-4 focused
     sub-questions (a plain prompt, not a tool call),
  2. retrieves independently for each sub-question against the same
     shared Pinecone index,
  3. checks whether the combined retrieved set is actually relevant
     (`retrieval.retriever.is_grounded`),
  4. generates one final answer with GPT-4o-mini from all the
     multi-query context, either grounded in the retrieved passages
     or -- if the knowledge base has nothing relevant -- as a
     clearly-flagged, ungrounded answer from general knowledge.
"""

import json
import logging
from typing import Any, Dict, List

from backend.config import COMPLEX_TOP_K
from backend.llm.openai_client import chat
from backend.retrieval.retriever import is_grounded, retrieve

logger = logging.getLogger(__name__)

DECOMPOSE_SYSTEM_PROMPT = """You break down a user's question into a small set of \
focused sub-questions that, together, cover everything needed to answer it fully.

Rules:
- Return 2 to 4 sub-questions. Use fewer if the question is only moderately complex.
- Each sub-question should be self-contained and specific enough to search a \
knowledge base with.
- Respond with ONLY a JSON array of strings, nothing else. Example:
["sub-question 1", "sub-question 2"]"""

GROUNDED_SYNTHESIZE_SYSTEM_PROMPT = """You are a helpful assistant. You were given a \
complex question, which was broken into sub-questions, and each sub-question was \
searched against a knowledge base. Using ONLY the retrieved passages below, \
synthesize one coherent, well-organized final answer to the ORIGINAL question. Do \
not include citation markers or source numbering in your answer -- just write the \
answer in plain prose. If the passages don't fully cover something, say so rather \
than guessing."""

UNGROUNDED_SYNTHESIZE_SYSTEM_PROMPT = """You are a helpful assistant. A complex \
question was broken into sub-questions and each was searched against a knowledge \
base, but nothing relevant enough was found for any of them. Answer the ORIGINAL \
question from your own general knowledge if you can, but start your reply with a \
short note that this answer is NOT based on the uploaded documents."""


def _decompose(query: str) -> List[str]:
    raw = chat(prompt=query, system=DECOMPOSE_SYSTEM_PROMPT)
    try:
        sub_queries = json.loads(raw)
        if isinstance(sub_queries, list) and all(isinstance(q, str) for q in sub_queries):
            cleaned = [q.strip() for q in sub_queries if q.strip()]
            if cleaned:
                return cleaned[:4]
    except json.JSONDecodeError:
        pass

    logger.warning("Could not parse decomposition output %r; falling back to original query.", raw)
    return [query]


def run_complex_pipeline(query: str) -> Dict[str, Any]:
    """
    Returns:
        {
            "answer": str,
            "sources": [{"source": ..., "text": ..., "score": ...}, ...],
            "grounded": bool,
            "trace": [str, ...],
        }
    """
    trace = ["Routed to COMPLEX pipeline (decompose -> multi-query retrieval -> GPT-4o-mini generation)."]

    sub_queries = _decompose(query)
    trace.append(f"Decomposed into {len(sub_queries)} sub-question(s): {sub_queries}")

    all_matches: List[Dict[str, Any]] = []
    context_blocks = []

    for sub_query in sub_queries:
        matches = retrieve(sub_query, top_k=COMPLEX_TOP_K)
        trace.append(f"Retrieved {len(matches)} passage(s) for sub-question: {sub_query!r}")

        for m in matches:
            all_matches.append(m)
            context_blocks.append(
                f"(source: {m.get('source', 'unknown')}, "
                f"score: {m.get('score', 0):.3f}, sub-question: {sub_query})\n"
                f"{m.get('text', '').strip()}"
            )

    grounded = is_grounded(all_matches)
    best_score = max((m.get("score", 0.0) for m in all_matches), default=0.0)
    trace.append(f"Best match score across all sub-questions: {best_score:.3f} -> "
                 f"{'grounded' if grounded else 'out of context, falling back to general knowledge'}.")

    if grounded:
        context_text = "\n\n".join(context_blocks)
        prompt = (
            f"ORIGINAL QUESTION:\n{query}\n\n"
            f"SUB-QUESTIONS INVESTIGATED:\n" + "\n".join(f"- {q}" for q in sub_queries) + "\n\n"
            f"RETRIEVED PASSAGES:\n{context_text}\n\nWrite the final answer now."
        )
        answer = chat(prompt=prompt, system=GROUNDED_SYNTHESIZE_SYSTEM_PROMPT)
    else:
        prompt = (
            f"ORIGINAL QUESTION:\n{query}\n\n"
            f"SUB-QUESTIONS INVESTIGATED:\n" + "\n".join(f"- {q}" for q in sub_queries) + "\n\n"
            f"(No sufficiently relevant passages were found for any sub-question.)"
        )
        answer = chat(prompt=prompt, system=UNGROUNDED_SYNTHESIZE_SYSTEM_PROMPT)

    trace.append("Synthesized final answer.")
    return {"answer": answer, "sources": all_matches, "grounded": grounded, "trace": trace}
