"""
Simple path: direct retrieve -> answer, generated by Llama3.2:3b (Ollama).

No tool-calling, no model-driven retrieval decisions -- the classifier
already decided this query is "simple", so this pipeline always:
  1. retrieves once with the raw user query,
  2. checks whether what came back is actually relevant
     (`retrieval.retriever.is_grounded`),
  3. generates one final answer with Llama3.2:3b, either grounded in
     the retrieved passages or -- if the knowledge base has nothing
     relevant for this query -- as a clearly-flagged, ungrounded
     answer from the model's own general knowledge.
"""

import logging
from typing import Any, Dict

from backend.config import SIMPLE_TOP_K
from backend.llm.ollama_client import chat
from backend.retrieval.retriever import format_context, is_grounded, retrieve

logger = logging.getLogger(__name__)

GROUNDED_SYSTEM_PROMPT = """You are a helpful assistant. Answer the user's question \
using ONLY the retrieved passages below. Do not include citation markers or source \
numbering in your answer -- just write the answer in plain prose. If the passages \
don't fully answer the question, say what's missing rather than guessing."""

UNGROUNDED_SYSTEM_PROMPT = """You are a helpful assistant. The knowledge base was \
searched but nothing relevant enough to the user's question was found. Answer from \
your own general knowledge if you can, but start your reply with a short note that \
this answer is NOT based on the uploaded documents."""


def run_simple_pipeline(query: str) -> Dict[str, Any]:
    """
    Returns:
        {
            "answer": str,
            "sources": [{"source": ..., "text": ..., "score": ...}, ...],
            "grounded": bool,
            "trace": [str, ...],
        }
    """
    trace = ["Routed to SIMPLE pipeline (single retrieval -> Llama3.2:3b generation)."]

    matches = retrieve(query, top_k=SIMPLE_TOP_K)
    trace.append(f"Retrieved {len(matches)} passage(s) for the raw query.")

    grounded = is_grounded(matches)
    best_score = max((m.get("score", 0.0) for m in matches), default=0.0)
    trace.append(f"Best match score: {best_score:.3f} -> {'grounded' if grounded else 'out of context, falling back to general knowledge'}.")

    if grounded:
        prompt = f"QUESTION:\n{query}\n\nRETRIEVED PASSAGES:\n{format_context(matches)}\n\nAnswer now."
        answer = chat(prompt=prompt, system=GROUNDED_SYSTEM_PROMPT)
    else:
        prompt = f"QUESTION:\n{query}\n\n(No sufficiently relevant passages were found in the knowledge base.)"
        answer = chat(prompt=prompt, system=UNGROUNDED_SYSTEM_PROMPT)

    return {"answer": answer, "sources": matches, "grounded": grounded, "trace": trace}
